name: main

on:
  push:
    branches:
      - 'main'

env: # тег, под которым будет храниться временный образ-кеш
  TEST_TAG: grevtsevalex/app-image:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v2

      # Ниже список шагов из документации build-push-action
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        # Эти секреты нужно добавить самостоятельно
        # Получить https://docs.docker.com/docker-hub/access-tokens/
        # Добавить https://docs.github.com/en/actions/security-guides/encrypted-secrets
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Сборка и сразу кеширование, чтобы повторный запуск был быстрее
      - uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      # Запуск тестов, команда запуска зависит от стека
      # Лучше ее спрятать за make
      # - run: docker run --rm ${{ env.TEST_TAG }} npm test
      # Здесь же нужно настроить запуск линтера

      # Заливаем протестированный образ на Docker Hub
      # https://github.com/docker/build-push-action/blob/master/docs/advanced/test-before-push.md
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: grevtsevalex/app-image:latest
