name: release

on:
  create:
    tags:
      - v* # только теги начинающиеся с v: v1, v2, v5

env:
  APP_IMAGE_NAME: grevtsevalex/app-image

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Ниже список шагов из документации build-push-action
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        # Эти секреты нужно добавить самостоятельно
        # Получить https://docs.docker.com/docker-hub/access-tokens/
        # Добавить https://docs.github.com/en/actions/security-guides/encrypted-secrets
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      # Скачиваем образ
      - run: docker pull ${{ env.APP_IMAGE_NAME }}:latest
      # Тегируем, тег в образе совпадает с тегом git-репозитория
      # github.ref_name - в данном случае имя тега
      - run: docker tag ${{ env.APP_IMAGE_NAME }}:latest ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}

      # Заливаем новый тег
      - run: docker push ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}